name: deploy-book

on:
  push:
    branches:
      - main

env:
  BASE_URL: /${{ github.event.repository.name }}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install quarto-cli plotly ipywidgets

      - name: Check Quarto version
        run: quarto --version

      - name: Build the book
        run: quarto render chapters

      - name: Debug - Check if HTML build exists
        run: ls -la chapters/_site || echo "_site directory missing!"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: "github-pages"
          path: "chapters/_site"

      - name: Debug - List uploaded artifacts
        run: ls -la ${{ runner.temp }}/pages-artifact/ || echo "No artifacts uploaded!"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "github-pages"
