name: deploy-quarto

on:
  push:
    branches:
      - main

jobs:
  deploy-quarto:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install quarto-cli plotly ipywidgets

      - name: Check Quarto version
        run: quarto --version

      - name: Build Quarto book
        run: quarto render  # Quarto will use quarto.yml at repo root
          
      - name: Debug - Check if _site exists
        run: ls -la _site || echo "_site directory missing!"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: "github-pages"
          path: "_site"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "github-pages"
